#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

if [ ! -e bin/rancher-cni-ipam ]; then
    ./scripts/build
fi

mkdir -p dist/artifacts
cd bin/
tar cvzf ../dist/artifacts/rancher-cni-ipam-${VERSION}.tar.gz .
